# -*- coding: utf-8 -*-
"""RBIF125_Week5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJmY1J4VlOTFkdRHCtjBP3SF3tbL2-vO

Install the medminst library
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install medmnist

"""Load the PneumoiniaMNIST dataset from MedMNIST"""

import medmnist
from medmnist import PneumoniaMNIST
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

# Define any transformations (e.g., convert to PyTorch tensors)
data_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# 1. Download and load the datasets
train_dataset = PneumoniaMNIST(split='train', transform=data_transform, download=True)
val_dataset = PneumoniaMNIST(split='val', transform=data_transform, download=True)
test_dataset = PneumoniaMNIST(split='test', transform=data_transform, download=True)

# 2. Wrap them in PyTorch DataLoaders for your model
batch_size = 128
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)

"""Build CNN model"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class CNN_Model(nn.Module):
  def __init__(self):
    super(CNN_Model, self).__init__()

    # Layer 1: input single image, 3x3 filter, 16 filter outputs
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, padding=1)
    #Layer 2: input 16 filter ouputs from layer 1, 3x3 filter, ouput 32 filter ouputs
    self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)

    #Pool the layers to reduce spatial dimesnions (2x2 filter)
    self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

    #Connect the pooled layers
    self.connected1 = nn.Linear(32 * 7 * 7, 128)
    #Output for binary image classification
    self.connected2 = nn.Linear(128, 1)

  def forward(self, x):
    #x is the input image and self is the model run for that input image
    #Layer 1 into ReLu activation function into pooling
    x = self.pool(F.relu(self.conv1(x)))
    #Layer 2 into ReLu activation function into pooling
    x = self.pool(F.relu(self.conv2(x)))
    #Flatten tensor
    x = torch.flatten(x, start_dim=1)
    #Connect layers using the flattened tensor
    x = F.relu(self.connected1(x))
    x = self.connected2(x)
    #Return the logit value
    return x

#Initiazlie model
model = CNN_Model()
print(model)

"""Set the device to cuda which should allow the model to run using the GPU"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"{device}") # This should print 'cuda'

"""Train the model using the train dataset"""

import torch.optim as optim
from tqdm import tqdm

#Run model using the GPU
model = model.to(device)

#Define loss function (using BCEWithLogitsLoss for binary classification) and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)

num_epochs=15
for epoch in range(num_epochs):
 # Iterate over training batches
   print(f"Epoch [{epoch + 1}/{num_epochs}]")

   for batch_index, (data, targets) in enumerate(tqdm(train_loader)):
       data = data.to(device)
       targets = targets.to(device).float()
       optimizer.zero_grad()
       scores = model(data)
       loss = criterion(scores, targets)
       loss.backward()
       optimizer.step()

"""Validate model using the validation dataset"""

# Use pytorch evalution mode
model.eval()

correct = 0
total = 0

# Run pytorch with no graideints for faster processing
with torch.no_grad():
    for data, targets in val_loader:
        data = data.to(device)
        targets = targets.to(device).float()

        # Grab the logits from the model ouput
        scores = model(data)

        # Apply sigmoid function to logits to fit into binary classification
        predictions = torch.sigmoid(scores)

        # Create binary threshold
        binary_classes = (predictions >= 0.5).float()

        # Count how many predictions matched the true targets
        total += targets.size(0)
        correct += (binary_classes == targets).sum().item()

accuracy = (correct / total) * 100
print(f"Validation Accuracy: {accuracy:.2f}%")

"""Test the model using the test dataset
*Uses the same structure as the validation loop
"""

# Use pytorch evalution mode
model.eval()

correct = 0
total = 0

# Run pytorch with no graideints for faster processing
with torch.no_grad():
    for data, targets in test_loader:
        data = data.to(device)
        targets = targets.to(device).float()

        # Grab the logits from the model ouput
        scores = model(data)

        # Apply sigmoid function to logits to fit into binary classification
        predictions = torch.sigmoid(scores)

        # Create binary threshold
        binary_classes = (predictions >= 0.5).float()

        # Count how many predictions matched the true targets
        total += targets.size(0)
        correct += (binary_classes == targets).sum().item()

test_accuracy = (correct / total) * 100
print(f"Test Accuracy: {test_accuracy: .2f}%")